### ISSUE TITLE
`KeyError: 'detail'` exception raised when submitting invalid jobs

### ISSUE THREAD

**Issue by asjohnston-asf** [ASFHyP3/hyp3-sdk#150]
For example, this error can be reproduced by submitting any job with a `name` longer than the allowed twenty characters:
```
>>> import hyp3_sdk
>>> hyp3 = hyp3_sdk.HyP3()
>>> hyp3.submit_rtc_job('S1A_IW_SLC__1SSV_20150621T120220_20150621T120232_006471_008934_72D8', name='this name is longer than twenty characters')
Traceback (most recent call last):
  File "/home/asjohnston/miniconda3/lib/python3.9/site-packages/hyp3_sdk/exceptions.py", line 29, in _raise_for_hyp3_status
    response.raise_for_status()
  File "/home/asjohnston/miniconda3/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://hyp3-api.asf.alaska.edu/jobs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/asjohnston/miniconda3/lib/python3.9/site-packages/hyp3_sdk/hyp3.py", line 266, in submit_rtc_job
    return self.submit_prepared_jobs(prepared_jobs=job_dict)
  File "/home/asjohnston/miniconda3/lib/python3.9/site-packages/hyp3_sdk/hyp3.py", line 187, in submit_prepared_jobs
    _raise_for_hyp3_status(response)
  File "/home/asjohnston/miniconda3/lib/python3.9/site-packages/hyp3_sdk/exceptions.py", line 32, in _raise_for_hyp3_status
    raise HyP3Error(f'{response} {response.json()["detail"]}')
KeyError: 'detail'
```

This issue in introduced by https://github.com/ASFHyP3/hyp3/issues/625 . `hyp3_sdk.exceptions` expects all HTTP 400 responses from the API to have a `detail` field that contains the error message, but the API is not including that field for any validation errors encountered when validating the job against the API's openapi scema.

**Comment by asjohnston-asf** [comment]
The underlying issue https://github.com/ASFHyP3/hyp3/issues/625 has been resolved.
