### ISSUE TITLE
`ServerError` from HyP3 constructor for users with many past jobs

### ISSUE THREAD

**Issue by asjohnston-asf** [ASFHyP3/hyp3-sdk#280]
```
[ERROR] ServerError
Traceback (most recent call last):
  File "/var/lang/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/var/task/main.py", line 28, in <module>
    HYP3 = sdk.HyP3(
  File "/var/task/hyp3_sdk/hyp3.py", line 49, in __init__
    self._check_application_status()
  File "/var/task/hyp3_sdk/hyp3.py", line 53, in _check_application_status
    info = self.my_info()
  File "/var/task/hyp3_sdk/hyp3.py", line 502, in my_info
    _raise_for_hyp3_status(response)
  File "/var/task/hyp3_sdk/exceptions.py", line 33, in _raise_for_hyp3_status
    raise ServerError
```

As of hyp3_sdk v6.2.0, hyp3_sdk.HyP3() now calls `HyP3.my_info()` to check the user's application status when they create a HyP3 session. For users with many past jobs, this results in a `504 Server Error: Gateway Timeout` error from the HyP3 API due to the lambda function hitting its 30s timeout. See https://github.com/ASFHyP3/hyp3/issues/1312

**Comment by jtherrmann** [comment]
The change from v6.2.0 has been reverted in v7.0.1 (see https://github.com/ASFHyP3/hyp3-sdk/issues/285) so I think we can close this issue.
