### ISSUE TITLE
Connection reset error, unable to get job by id

### ISSUE THREAD

**Issue by rbavery** [ASFHyP3/hyp3-sdk#88]
**Describe the bug**
 I received a connection reset error when a batch job was starting after many batch jobs successfully were submitted, ran, and were completed.

**To Reproduce**
I ran this script, using these id lists: [small_AOI_granule_lists.zip](https://github.com/ASFHyP3/hyp3-sdk/files/6114044/small_AOI_granule_lists.zip)

```python
from hyp3_sdk import HyP3
from glob import glob
import pandas as pd
from toolz import partition_all
import os
hyp3 = HyP3(username='', password='')
names = ["Kalimatan", "Kisangani", "Brazil"]
csvs = glob("../data/*csv")
aoi_granule_batches = []
for csv in csvs:
    aoi_granules = pd.read_csv(csv)["Granule Name"].tolist()
    batches_lst = list(partition_all(200, aoi_granules))
    aoi_granule_batches.append(batches_lst)

container_path = "/datadrive/storagentvk7fg5ozidg/sardiscovery/"

for aoi, aname in zip(aoi_granule_batches, names):
    for batch in aoi:
        print(len(batch))
        for granule in batch:
            name = aname[0:2]+granule[-34:-26]+granule[-4:]
            running_jobs = hyp3.find_jobs(status="RUNNING") + hyp3.find_jobs(status="PENDING")
            if len(running_jobs) < 200:
                hyp3.submit_rtc_job(granule=granule, name=name)
            else:
                batch = hyp3.find_jobs()
                batch = hyp3.watch(batch)

```

**Expected behavior**
Many batches completed succesfully but when one of them was starting an error occurred and it looks like the sdk couldn't wait for completion because it couldn't find a job id.

**Additional context**
Here is the full stack trace. Happy to provide more info that helps diagnose this issue.

```python
(py38) ryan@vmName:~/work/ms-sar-deforestation-internal/scripts$ python large_order_asf.py
200
/anaconda/envs/py38/lib/python3.8/site-packages/hyp3_sdk/hyp3.py:71: UserWarning: Found zero jobs
  warnings.warn('Found zero jobs', UserWarning)
200
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 221/221 [timeout in 9120s]
200
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 421/421 [timeout in 9480s]
200
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 621/621 [timeout in 9840s]
200
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 821/821 [timeout in 9900s]
200
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1021/1021 [timeout in 10080s]
200
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1221/1221 [timeout in 10200s]
200
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1421/1421 [timeout in 10260s]
200
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1621/1621 [timeout in 10260s]
200
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1821/1821 [timeout in 10320s]
200
  0%|                                                                                                                                                                          | 0/2021 [timeout in 10800 s]
Traceback (most recent call last):
  File "/anaconda/envs/py38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/anaconda/envs/py38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/anaconda/envs/py38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/anaconda/envs/py38/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/anaconda/envs/py38/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/anaconda/envs/py38/lib/python3.8/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/envs/py38/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/anaconda/envs/py38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/anaconda/envs/py38/lib/python3.8/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/anaconda/envs/py38/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/anaconda/envs/py38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/anaconda/envs/py38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/anaconda/envs/py38/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/anaconda/envs/py38/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/anaconda/envs/py38/lib/python3.8/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/envs/py38/lib/python3.8/site-packages/hyp3_sdk/hyp3.py", line 84, in get_job_by_id
    response = self.session.get(urljoin(self.url, f'/jobs/{job_id}'))
  File "/anaconda/envs/py38/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/anaconda/envs/py38/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/anaconda/envs/py38/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/anaconda/envs/py38/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "large_order_asf.py", line 27, in <module>
    batch = hyp3.watch(batch)
  File "/anaconda/envs/py38/lib/python3.8/functools.py", line 912, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/anaconda/envs/py38/lib/python3.8/site-packages/hyp3_sdk/hyp3.py", line 110, in _watch_batch
    batch = self.refresh(batch)
  File "/anaconda/envs/py38/lib/python3.8/functools.py", line 912, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/anaconda/envs/py38/lib/python3.8/site-packages/hyp3_sdk/hyp3.py", line 156, in _refresh_batch
    jobs.append(self.refresh(job))
  File "/anaconda/envs/py38/lib/python3.8/functools.py", line 912, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/anaconda/envs/py38/lib/python3.8/site-packages/hyp3_sdk/hyp3.py", line 161, in _refresh_job
    return self.get_job_by_id(job.job_id)
  File "/anaconda/envs/py38/lib/python3.8/site-packages/hyp3_sdk/hyp3.py", line 87, in get_job_by_id
    raise HyP3Error(f'Unable to get job by ID {job_id}')
hyp3_sdk.exceptions.HyP3Error: Unable to get job by ID a8ef7ffd-c0c6-49cb-b4ea-ac5b96fabfc1
```

**Comment by jhkennedy** [comment]
Hi @rbavery this looks like an upsteam issue with Requests --> urllib3:
* https://github.com/psf/requests/issues/4664
* https://github.com/urllib3/urllib3/pull/1911

Basically, Requests tries to keep your session alive, but depending on timing of the server disconnecting the session, Requests/urllib3 sometimes fails to reconnect/retry. 

--- 

Looking at your script, you don't need  to worry about this part:
```python
running_jobs = hyp3.find_jobs(status="RUNNING") + hyp3.find_jobs(status="PENDING")
            if len(running_jobs) < 200:
                hyp3.submit_rtc_job(granule=granule, name=name)
```

Our queues can handle you just jamming all your jobs in at once, and it actually will be a little cheaper for us (we can leverage autoscale better). So, you can just run through everything, submit them all, and come back later to find and watch. 

The API limits are around `POST` requests (200 jobs per `POST`) -- the `submit_rtc_job` method makes a `POST` request for each submit (1 job per `POST`). 

You could also prepare a list of  200 jobs at a time with `prepare_rtc_job` (returns a job *dictionary*) and submit them with `submit_prepared_jobs` -- `submit_prepared_jobs` will `POST` the entire job list at once and error if the job list is longer than 200. There's no real need to prepare and submit though; you just might see slightly better API performance.

**Comment by rbavery** [comment]
Ah, awesome that's helpful to know I can just submit everything at once. I'll try this out, thanks @jhkennedy

**Comment by rbavery** [comment]
Reopening just to note that I received an error using the method suggested of submitting many individual jobs

I iterated through all the granules I hadn't already submitted for a particular aoi.

```python
for batch in truncated_granule_batches:
    print(len(batch))
    for granule in batch:
        name = granule[-34:-26]+"_"+granule[-4:]
        hyp3.submit_rtc_job(granule=granule, name=name)
```

but got this error after a while.
```python
---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
/anaconda/envs/py38/lib/python3.8/site-packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    444                     # Otherwise it looks like a bug in the code.
--> 445                     six.raise_from(e, None)
    446         except (SocketTimeout, BaseSSLError, SocketError) as e:

/anaconda/envs/py38/lib/python3.8/site-packages/urllib3/packages/six.py in raise_from(value, from_value)

/anaconda/envs/py38/lib/python3.8/site-packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    439                 try:
--> 440                     httplib_response = conn.getresponse()
    441                 except BaseException as e:

/anaconda/envs/py38/lib/python3.8/http/client.py in getresponse(self)
   1346             try:
-> 1347                 response.begin()
   1348             except ConnectionError:

/anaconda/envs/py38/lib/python3.8/http/client.py in begin(self)
    306         while True:
--> 307             version, status, reason = self._read_status()
    308             if status != CONTINUE:

/anaconda/envs/py38/lib/python3.8/http/client.py in _read_status(self)
    267     def _read_status(self):
--> 268         line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
    269         if len(line) > _MAXLINE:

/anaconda/envs/py38/lib/python3.8/socket.py in readinto(self, b)
    668             try:
--> 669                 return self._sock.recv_into(b)
    670             except timeout:

/anaconda/envs/py38/lib/python3.8/ssl.py in recv_into(self, buffer, nbytes, flags)
   1240                   self.__class__)
-> 1241             return self.read(nbytes, buffer)
   1242         else:

/anaconda/envs/py38/lib/python3.8/ssl.py in read(self, len, buffer)
   1098             if buffer is not None:
-> 1099                 return self._sslobj.read(len, buffer)
   1100             else:

TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

ReadTimeoutError                          Traceback (most recent call last)
/anaconda/envs/py38/lib/python3.8/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    438             if not chunked:
--> 439                 resp = conn.urlopen(
    440                     method=request.method,

/anaconda/envs/py38/lib/python3.8/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    754 
--> 755             retries = retries.increment(
    756                 method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

/anaconda/envs/py38/lib/python3.8/site-packages/urllib3/util/retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    530             if read is False or not self._is_method_retryable(method):
--> 531                 raise six.reraise(type(error), error, _stacktrace)
    532             elif read is not None:

/anaconda/envs/py38/lib/python3.8/site-packages/urllib3/packages/six.py in reraise(tp, value, tb)
    734                 raise value.with_traceback(tb)
--> 735             raise value
    736         finally:

/anaconda/envs/py38/lib/python3.8/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    698             # Make the request on the httplib connection object.
--> 699             httplib_response = self._make_request(
    700                 conn,

/anaconda/envs/py38/lib/python3.8/site-packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    446         except (SocketTimeout, BaseSSLError, SocketError) as e:
--> 447             self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
    448             raise

/anaconda/envs/py38/lib/python3.8/site-packages/urllib3/connectionpool.py in _raise_timeout(self, err, url, timeout_value)
    352         ):  # Python < 2.7.4
--> 353             raise ReadTimeoutError(
    354                 self, url, "Read timed out. (read timeout=%s)" % timeout_value

ReadTimeoutError: HTTPSConnectionPool(host='hyp3-api.asf.alaska.edu', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

ReadTimeout                               Traceback (most recent call last)
<ipython-input-13-09674d96b6df> in <module>
      3     for granule in batch:
      4         name = granule[-34:-26]+"_"+granule[-4:]
----> 5         hyp3.submit_rtc_job(granule=granule, name=name)

/anaconda/envs/py38/lib/python3.8/site-packages/hyp3_sdk/hyp3.py in submit_rtc_job(self, granule, name, **kwargs)
    232         """
    233         job_dict = self.prepare_rtc_job(granule, name=name, **kwargs)
--> 234         return self.submit_prepared_jobs(prepared_jobs=job_dict)
    235 
    236     @classmethod

/anaconda/envs/py38/lib/python3.8/site-packages/hyp3_sdk/hyp3.py in submit_prepared_jobs(self, prepared_jobs)
    175             payload = {'jobs': prepared_jobs}
    176 
--> 177         response = self.session.post(urljoin(self.url, '/jobs'), json=payload)
    178         try:
    179             response.raise_for_status()

/anaconda/envs/py38/lib/python3.8/site-packages/requests/sessions.py in post(self, url, data, json, **kwargs)
    588         """
    589 
--> 590         return self.request('POST', url, data=data, json=json, **kwargs)
    591 
    592     def put(self, url, data=None, **kwargs):

/anaconda/envs/py38/lib/python3.8/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    540         }
    541         send_kwargs.update(settings)
--> 542         resp = self.send(prep, **send_kwargs)
    543 
    544         return resp

/anaconda/envs/py38/lib/python3.8/site-packages/requests/sessions.py in send(self, request, **kwargs)
    653 
    654         # Send the request
--> 655         r = adapter.send(request, **kwargs)
    656 
    657         # Total elapsed time of the request (approximately)

/anaconda/envs/py38/lib/python3.8/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    527                 raise SSLError(e, request=request)
    528             elif isinstance(e, ReadTimeoutError):
--> 529                 raise ReadTimeout(e, request=request)
    530             else:
    531                 raise

ReadTimeout: HTTPSConnectionPool(host='hyp3-api.asf.alaska.edu', port=443): Read timed out. (read timeout=None)
```

**Comment by rbavery** [comment]
When I submitted the jobs in batches of 200, the jobs went through very quickly with no timeout errors, which might be because some of my previous running jobs completed? I'm not sure. Feel free to close if you think the above timeout is not an issue.

**Comment by jhkennedy** [comment]
Since we've not seen this issue in a while, I'm closing.
